import = [
	"~/.config/alacritty/themes/themes/nightfox.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 150
dimensions.lines = 50
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.99
# blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
# normal.family = "DroidSansM Nerd Font"
offset.y = 3
size = 16.5
